"""
Constants and definitions for server packets.

This module contains packet definitions and constants used for communication
between the server and clients.
"""

from server.utils.time_utils import encode_ingame_time
from utils.bitstream_utils import simple_bit_stream


class server_packets:
    """Container for server-to-client packet definitions."""

    # Initialization packet sent to new clients when they connect
    INIT_PACKET = bytes([0x0A, 0x00, 0xC8, 0x00, 0x6C, 0x07, 0x00, 0x00, 0x40, 0x0E])

    # Transmission end packet
    TRANSMISSION_END_PACKET = bytes([0x04, 0x00, 0xF4, 0x01])

    def get_server_credentials(player_index: int) -> bytes:
        stream = simple_bit_stream()
        current_time = encode_ingame_time()
        stream.write_bytes(bytes([0x38, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(bytes([0x08, 0x40, 0x20, 0x10]))
        stream.write_bytes(current_time)
        stream.write_bytes(
            bytes(
                [
                    0x7C,
                    0x12,
                    0x02,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x1A,
                    0x3B,
                    0x12,
                    0x01,
                    0x00,
                    0xFF,
                    0xFF,
                    0xFF,
                    0xFF,
                    0xFF,
                    0xFF,
                    0xFF,
                    0xFF,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x8D,
                    0x9D,
                    0x01,
                    0x00,
                    0x00,
                    0x00,
                ]
            )
        )
        return stream.to_bytes()

    def get_character_select_start_data(player_index: int) -> bytes:
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0x52, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(
            bytes(
                [
                    0x08,
                    0x40,
                    0x80,
                    0x10,
                    0x01,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                ]
            )
        )
        return stream.to_bytes()

    def get_new_character_data(player_index: int) -> bytes:
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0x6C, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(
            bytes(
                [
                    0x08,
                    0x40,
                    0x60,
                    0x79,
                    0x91,
                    0x01,
                    0x90,
                    0x01,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x0C,
                    0xC8,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0xC8,
                    0x00,
                    0x90,
                    0x01,
                    0x90,
                    0x01,
                    0x10,
                    0x00,
                    0x10,
                    0x00,
                    0x10,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x10,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0xFC,
                    0xFF,
                    0xFF,
                    0xFF,
                    0x03,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                ]
            )
        )
        return stream.to_bytes()

    def character_name_already_taken(player_index: int) -> bytes:
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0x0E, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(bytes([0x08, 0x40, 0x00, 0x01, 0x00]))
        return stream.to_bytes()

    def character_name_check_success(player_index: int) -> bytes:
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0x0E, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(bytes([0x08, 0x40, 0x80, 0x00, 0x00]))
        return stream.to_bytes()

    def connection_error(player_index: int) -> bytes:
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0x0E, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(bytes([0x08, 0x40, 0xA0, 0x00, 0x00]))
        return stream.to_bytes()

    def new_character_world_data(player_index: int) -> bytes:
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0xA8, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(
            bytes(
                [
                    0x08,
                    0x40,
                    0x61,
                    0x02,
                    0x00,
                    0x0A,
                    0x82,
                    0xA0,
                    0xC3,
                    0xE1,
                    0x0C,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x50,
                    0x10,
                    0x84,
                    0x9D,
                    0x0F,
                    0x67,
                    0x00,
                    0xA0,
                    0x25,
                    0x26,
                    0x80,
                    0x10,
                    0x7D,
                    0x38,
                    0x03,
                    0x00,
                    0x14,
                    0x24,
                    0x60,
                    0xA7,
                    0x20,
                    0x08,
                    0x14,
                    0x20,
                    0xCE,
                    0x00,
                    0x64,
                    0x00,
                    0x00,
                    0x00,
                    0x0D,
                    0x1C,
                    0x02,
                    0x05,
                    0x00,
                    0x00,
                    0x80,
                    0xC6,
                    0x46,
                    0x40,
                    0x40,
                    0x63,
                    0x83,
                    0xAC,
                    0xCC,
                    0xCC,
                    0xAC,
                    0x6C,
                    0x8C,
                    0x6E,
                    0x8E,
                    0x8B,
                    0x0B,
                    0xC0,
                    0xA9,
                    0xEC,
                    0x0E,
                    0x64,
                    0x0C,
                    0x2D,
                    0x4C,
                    0x0E,
                    0x24,
                    0xCD,
                    0x0D,
                    0xE4,
                    0x2C,
                    0xAC,
                    0xAD,
                    0x4C,
                    0x07,
                    0x64,
                    0xC9,
                    0xAD,
                    0x8C,
                    0x0D,
                    0x2E,
                    0x6C,
                    0x2C,
                    0x0C,
                    0x04,
                    0x65,
                    0xC9,
                    0xAD,
                    0x8C,
                    0x0D,
                    0x2E,
                    0x6C,
                    0x2C,
                    0x0C,
                    0x04,
                    0x25,
                    0xA6,
                    0x46,
                    0xC5,
                    0x65,
                    0xAE,
                    0xCC,
                    0x0C,
                    0xE0,
                    0x2B,
                    0x26,
                    0x25,
                    0xC5,
                    0x45,
                    0x01,
                    0xC0,
                    0x89,
                    0x08,
                    0x64,
                    0x0C,
                    0x2D,
                    0x4C,
                    0xEE,
                    0x8B,
                    0xAC,
                    0x8C,
                    0xED,
                    0xCB,
                    0x8C,
                    0x2D,
                    0xEC,
                    0x0C,
                    0x84,
                    0xC7,
                    0x07,
                    0x24,
                    0x06,
                    0x84,
                    0x29,
                    0xA9,
                    0x29,
                    0x89,
                    0x0A,
                    0x24,
                    0x06,
                    0x00,
                    0x84,
                    0x29,
                    0xA9,
                    0x29,
                    0x89,
                    0x0A,
                    0x04,
                ]
            )
        )

        stream.write_bytes(bytes([0xBA, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x00]))
        stream.write_int(player_index, 16)
        stream.write_bytes(
            bytes(
                [
                    0x08,
                    0xC0,
                    0x02,
                    0xD0,
                    0x79,
                    0x11,
                    0xC8,
                    0xBD,
                    0x10,
                    0x44,
                    0x5E,
                    0x0C,
                    0x22,
                    0x2F,
                    0x08,
                    0xC9,
                    0x16,
                    0x85,
                    0xC8,
                    0x0B,
                    0x03,
                    0x58,
                    0x1C,
                    0xC0,
                    0x02,
                    0x01,
                    0x16,
                    0x09,
                    0xB0,
                    0x50,
                    0x80,
                    0xC5,
                    0x02,
                    0x2C,
                    0x18,
                    0x60,
                    0xD1,
                    0x00,
                    0x0B,
                    0x07,
                    0x59,
                    0x3C,
                    0xC8,
                    0x02,
                    0x02,
                    0x16,
                    0x11,
                    0xB0,
                    0x90,
                    0x80,
                    0xC5,
                    0x04,
                    0x2C,
                    0x28,
                    0x60,
                    0x51,
                    0x01,
                    0x0B,
                    0x0B,
                    0x58,
                    0x5C,
                    0xC0,
                    0x02,
                    0x13,
                    0x79,
                    0x91,
                    0x89,
                    0xBC,
                    0xD0,
                    0x44,
                    0x5E,
                    0x6C,
                    0xC0,
                    0x82,
                    0x03,
                    0x16,
                    0x1D,
                    0xB0,
                    0xF0,
                    0x80,
                    0xC5,
                    0x07,
                    0x2C,
                    0x40,
                    0x60,
                    0x11,
                    0x02,
                    0x0B,
                    0x11,
                    0x58,
                    0x8C,
                    0xC8,
                    0x82,
                    0x44,
                    0x16,
                    0x25,
                    0xB0,
                    0x30,
                    0x81,
                    0xC5,
                    0x89,
                    0x2D,
                    0x50,
                    0x60,
                    0x91,
                    0x02,
                    0x0B,
                    0x15,
                    0x58,
                    0xAC,
                    0x42,
                    0x2C,
                    0x58,
                    0x70,
                    0xD1,
                    0x82,
                    0x0B,
                    0x17,
                    0x58,
                    0xCC,
                    0xD0,
                    0x82,
                    0x06,
                    0x16,
                    0x35,
                    0xB0,
                    0xB0,
                    0xC1,
                    0xC6,
                    0x03,
                    0x84,
                    0x8F,
                    0x15,
                    0x35,
                    0xB1,
                    0x0F,
                    0x2B,
                    0x63,
                    0x91,
                    0x70,
                    0x20,
                    0x35,
                    0xD1,
                    0xF6,
                    0x43,
                    0xF2,
                    0x4F,
                    0x41,
                    0x10,
                    0x72,
                    0xA0,
                    0xD9,
                    0x01,
                    0x90,
                    0x01,
                    0x00,
                    0x00,
                    0x0A,
                    0x52,
                    0x90,
                    0x53,
                    0x0F,
                    0x00,
                    0x00,
                    0xD0,
                    0x00,
                    0x11,
                    0x70,
                    0xAA,
                    0x2A,
                    0x48,
                    0x41,
                    0x0E,
                    0x32,
                    0x00,
                    0x00,
                    0x00,
                ]
            )
        )

        stream.write_bytes(bytes([0x83, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x00]))
        stream.write_int(player_index, 16)
        stream.write_bytes(
            bytes(
                [
                    0x08,
                    0x40,
                    0x61,
                    0x02,
                    0x00,
                    0x0A,
                    0x82,
                    0x40,
                    0x11,
                    0x82,
                    0x0E,
                    0x40,
                    0x06,
                    0x00,
                    0x00,
                    0x50,
                    0x10,
                    0x84,
                    0x1C,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x80,
                    0x82,
                    0x20,
                    0xE8,
                    0x88,
                    0xA0,
                    0x03,
                    0x00,
                    0x00,
                    0x00,
                    0x00,
                    0x14,
                    0x04,
                    0x61,
                    0xA7,
                    0x0B,
                    0x1D,
                    0x00,
                    0x68,
                    0x89,
                    0x09,
                    0x20,
                    0x44,
                    0x5D,
                    0xE8,
                    0x00,
                    0x00,
                    0x05,
                    0x41,
                    0x98,
                    0x20,
                    0x48,
                    0x07,
                    0x68,
                    0x01,
                    0x00,
                    0x00,
                    0x28,
                    0x08,
                    0x02,
                    0x40,
                    0x2D,
                    0x3B,
                    0x00,
                    0x7D,
                    0x00,
                    0x00,
                    0x40,
                    0x41,
                    0x10,
                    0x70,
                    0x6C,
                    0xD9,
                    0x01,
                    0x06,
                    0x00,
                    0x00,
                    0x00,
                    0x0A,
                    0x12,
                    0x00,
                    0x50,
                    0x90,
                    0x80,
                    0x89,
                    0x82,
                    0x04,
                    0x50,
                    0x14,
                    0x24,
                    0x00,
                    0xA7,
                    0x20,
                    0x01,
                    0x3B,
                    0x05,
                    0x41,
                    0xA0,
                    0xC0,
                    0x41,
                    0x07,
                    0x20,
                    0x03,
                    0x00,
                    0x00,
                    0x68,
                    0xE0,
                    0x10,
                    0x28,
                    0x00,
                    0x00,
                    0x00,
                    0x34,
                    0x36,
                    0x02,
                    0x02,
                    0x00,
                ]
            )
        )

        return stream.to_bytes()

    @staticmethod
    def keepalive_6_seconds(player_index: int) -> bytes:
        """Generate a 6-second keepalive packet for the specified player."""
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0x13, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(
            bytes([0x08, 0xC0, 0x42, 0xA0, 0xFF, 0xD3, 0x90, 0x08, 0xB0, 0x07])
        )
        return stream.to_bytes()

    @staticmethod
    def keepalive_15_seconds(player_index: int) -> bytes:
        """Generate a 15-second keepalive packet for the specified player."""
        stream = simple_bit_stream()
        stream.write_bytes(bytes([0x10, 0x00, 0x2C, 0x01, 0x00, 0x00, 0x04]))
        stream.write_int(player_index, 16)
        stream.write_bytes(bytes([0x08, 0x40, 0x81, 0x93, 0xEE, 0xE4, 0x08]))
        return stream.to_bytes()


INIT_PACKET = server_packets.INIT_PACKET
TRANSMISSION_END_PACKET = server_packets.TRANSMISSION_END_PACKET
