"""
Data models for the PolyhedronEmu server.
"""

from .client_character import ClientCharacter
from .enums import (
    GameObjectKind,
    GameObjectType,
    ItemSuffix,
    KarmaTypes,
    Locale,
    Guild,
    ClanRank,
    BelongingSlot,
    ChatType,
    MonsterType,
    MainhandSlotState,
    Stat,
    Clan,
    DEFAULT_CLAN,
    MONSTER_NAME_TO_TYPE_MAPPING,
    MONSTER_TYPE_TO_NAME_MAPPING,
    HEALTH_AT_TITLE,
    HEALTH_AT_DEGREE,
    MP_AT_TITLE,
    MP_AT_DEGREE,
    AVAILABLE_STATS_PRIMARY,
    AVAILABLE_STATS_SECONDARY,
    STAT_BONUS_FOR_RESETS,
    XP_PER_LEVEL_BASE,
    XP_PER_LEVEL_DELTA,
)

__all__ = [
    "ClientCharacter",
    "GameObjectKind",
    "GameObjectType",
    "ItemSuffix",
    "KarmaTypes",
    "Locale",
    "Guild",
    "ClanRank",
    "BelongingSlot",
    "ChatType",
    "MonsterType",
    "MainhandSlotState",
    "Stat",
    "Clan",
    "DEFAULT_CLAN",
    "MONSTER_NAME_TO_TYPE_MAPPING",
    "MONSTER_TYPE_TO_NAME_MAPPING",
    "HEALTH_AT_TITLE",
    "HEALTH_AT_DEGREE",
    "MP_AT_TITLE",
    "MP_AT_DEGREE",
    "AVAILABLE_STATS_PRIMARY",
    "AVAILABLE_STATS_SECONDARY",
    "STAT_BONUS_FOR_RESETS",
    "XP_PER_LEVEL_BASE",
    "XP_PER_LEVEL_DELTA",
]
